namespace PicoActor.Abs;

/// <summary>
/// Framework-generated saga completion event. Triggered by MarkComplete(result) and
/// persisted atomically in the same batch as business events.
/// On replay the framework recognizes this event to restore _completed and does not
/// deliver it to the subclass Mutate.
/// <para>
/// <see cref="Result"/> is typed <c>object?</c> and is persisted with the event — with a
/// persistent store this requires polymorphic serialization support; keep it a simple
/// serializable type (record/string) as the design guidance requires.
/// </para>
/// </summary>
public sealed record SagaCompleted(object? Result) : IDomainEvent;

/// <summary>
/// Framework-generated saga failure event. Triggered by an unhandled business
/// exception (OnMessageAsync or ResumeAsync).
/// Reason is "exception type name + truncated message (≤512 chars)"; the exception
/// object itself is not serialized (AOT-safe).
/// <para>
/// Reason is persisted AND published to subscribers — exception messages can carry
/// sensitive data. Scrub at the raise site if the message is not safe to retain.
/// </para>
/// </summary>
public sealed record SagaFailed(string Reason) : IDomainEvent;

/// <summary>Result of ExecuteSaga: saga id + final result.</summary>
public sealed record SagaExecution<TResult>(Guid Id, TResult Result);

/// <summary>
/// Saga business-failure exception. Generated by SagaActor after a business
/// exception and used to fault the AskAsync caller's TCS.
/// Reason matches the SagaFailed event.
/// </summary>
public sealed class SagaExecutionException : Exception
{
    public Guid SagaId { get; }
    public string Reason { get; }

    public SagaExecutionException(Guid sagaId, string reason)
        : base($"Saga {sagaId} failed: {reason}")
    {
        SagaId = sagaId;
        Reason = reason;
    }
}

/// <summary>A single recovery result from ResumeInterruptedSagasAsync.</summary>
public sealed record SagaResumeResult(Guid Id, SagaResumeStatus Status, string? Reason = null);

/// <summary>Status classification of a saga after recovery.</summary>
public enum SagaResumeStatus
{
    Completed,
    Failed,
    Running,
}
