<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <Deterministic>true</Deterministic>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.9" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.301" />
    <PackageVersion Include="PicoActor" Version="$(Version)" />
    <PackageVersion Include="PicoActor.Abs" Version="$(Version)" />
    <PackageVersion Include="PicoDI" Version="2026.8.3" />
    <PackageVersion Include="PicoDI.Abs" Version="2026.8.3" />
    <PackageVersion Include="PicoLog.Abs" Version="2026.8.3" />
    <PackageVersion Include="PicoMediator" Version="2026.8.3" />
    <PackageVersion Include="PicoMediator.Abs" Version="2026.8.3" />
    <PackageVersion Include="PicoMediator.DI" Version="2026.8.3" />
    <PackageVersion Include="System.Threading.Channels" Version="10.0.9" />
    <PackageVersion Include="TUnit" Version="1.63.0" />
  </ItemGroup>
</Project>
