using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PicoActor.Gen;

/// <summary>
/// Declare-and-subscribe for PicoActor: scans closed, non-abstract
/// IDomainEventSubscriber&lt;TEvent&gt; implementations and emits a per-assembly
/// configurator (id "pico-actor::&lt;assembly&gt;") into MediatorAutoSubscriptionRegistry.
/// The configurator registers each handler (append semantics — multiple handlers
/// per event type are supported) and one envelope bridge per distinct event type.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ActorSubscriberGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var subscriberDeclarations = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax c && c.BaseList?.Types.Count > 0,
                transform: static (ctx, ct) => GetSubscriberInfos(ctx, ct)
            )
            .Where(static x => x.Length > 0)
            .SelectMany(static (x, _) => x);

        context.RegisterSourceOutput(
            context.CompilationProvider.Combine(subscriberDeclarations.Collect()),
            static (spc, pair) => GenerateRegistrations(spc, pair.Left, pair.Right)
        );
    }

    private sealed class SubscriberInfo
    {
        public SubscriberInfo(
            string eventTypeFqn,
            string implementationType,
            ImmutableArray<string> constructorParameterTypes
        )
        {
            EventTypeFqn = eventTypeFqn;
            ImplementationType = implementationType;
            ConstructorParameterTypes = constructorParameterTypes;
        }

        public string EventTypeFqn { get; }
        public string ImplementationType { get; }
        public ImmutableArray<string> ConstructorParameterTypes { get; }
    }

    private static ImmutableArray<SubscriberInfo> GetSubscriberInfos(
        GeneratorSyntaxContext ctx,
        CancellationToken ct
    )
    {
        if (ctx.Node is not ClassDeclarationSyntax classDecl)
            return [];

        var typeSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl, ct) as INamedTypeSymbol;
        var accessibility = typeSymbol?.DeclaredAccessibility;
        if (
            typeSymbol is null
            || typeSymbol.IsAbstract
            || typeSymbol.IsGenericType
            || (accessibility != Accessibility.Public && accessibility != Accessibility.Internal)
        )
            return [];

        var results = ImmutableArray.CreateBuilder<SubscriberInfo>();
        foreach (var iface in typeSymbol.AllInterfaces)
        {
            if (!iface.IsGenericType)
                continue;

            var constructed = iface.ConstructedFrom;
            if (constructed.ContainingNamespace.ToDisplayString() != "PicoActor.Abs")
                continue;
            if (constructed.MetadataName != "IDomainEventSubscriber`1")
                continue;

            var ctor = typeSymbol.InstanceConstructors.FirstOrDefault(c =>
                c.DeclaredAccessibility == Accessibility.Public && !c.IsStatic
            );
            var ctorParams = ctor is null
                ? []
                : ctor
                    .Parameters.Select(p =>
                        p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                    )
                    .ToImmutableArray();

            results.Add(
                new SubscriberInfo(
                    iface.TypeArguments[0].ToDisplayString(
                        SymbolDisplayFormat.FullyQualifiedFormat
                    ),
                    typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    ctorParams
                )
            );
        }

        return results.ToImmutable();
    }

    private static void GenerateRegistrations(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<SubscriberInfo> subscribers
    )
    {
        if (subscribers.IsDefaultOrEmpty)
            return;

        var assemblyName = compilation.AssemblyName ?? "Unknown";
        var safeAssemblyName = SanitizeIdentifier(assemblyName);
        var className = $"PicoActorSubscriberRegistrations_{safeAssemblyName}";
        var configuratorId = $"pico-actor::{assemblyName}";

        var distinctEventTypes = subscribers
            .Select(static s => s.EventTypeFqn)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(static x => x, StringComparer.Ordinal)
            .ToArray();

        var sb = new StringBuilder(8192);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace PicoActor.Generated;");
        sb.AppendLine();

        foreach (var eventType in distinctEventTypes)
        {
            var bridgeName = "PicoActorEnvelopeBridge_" + SanitizeIdentifier(eventType);
            sb.AppendLine(
                $"internal sealed class {bridgeName} : global::PicoMediator.Abs.ISubscriber<global::PicoActor.Abs.DomainEventEnvelope>"
            );
            sb.AppendLine("{");
            sb.AppendLine("    private readonly global::PicoDI.Abs.ISvcScope _scope;");
            sb.AppendLine();
            sb.AppendLine(
                $"    public {bridgeName}(global::PicoDI.Abs.ISvcScope scope) => _scope = scope;"
            );
            sb.AppendLine();
            sb.AppendLine(
                "    public async ValueTask Handle(global::PicoActor.Abs.DomainEventEnvelope envelope, global::System.Threading.CancellationToken ct)"
            );
            sb.AppendLine("    {");
            sb.AppendLine($"        if (envelope.Event is {eventType} e)");
            sb.AppendLine("        {");
            sb.AppendLine(
                $"            if (!_scope.TryGetServices(typeof(global::PicoActor.Abs.IDomainEventSubscriber<{eventType}>), out var rawHandlers))"
            );
            sb.AppendLine("                return;");
            sb.AppendLine(
                "            var sender = (global::PicoActor.Abs.ICommandSender)_scope.GetService(typeof(global::PicoActor.Abs.ICommandSender));"
            );
            sb.AppendLine(
                $"            var typed = new global::PicoActor.Abs.DomainEventEnvelope<{eventType}>(envelope.ActorId, envelope.Version, e);"
            );
            sb.AppendLine(
                "            global::System.Collections.Generic.List<global::System.Exception>? exceptions = null;"
            );
            sb.AppendLine("            foreach (var raw in rawHandlers)");
            sb.AppendLine("            {");
            sb.AppendLine("                try");
            sb.AppendLine("                {");
            sb.AppendLine(
                $"                    await ((global::PicoActor.Abs.IDomainEventSubscriber<{eventType}>)raw).Handle(typed, sender, ct).ConfigureAwait(false);"
            );
            sb.AppendLine("                }");
            sb.AppendLine("                catch (global::System.Exception ex)");
            sb.AppendLine("                {");
            sb.AppendLine("                    exceptions ??= [];");
            sb.AppendLine("                    exceptions.Add(ex);");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("            if (exceptions is { Count: > 0 })");
            sb.AppendLine(
                "                throw new global::System.AggregateException(exceptions);"
            );
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void AutoRegister()");
        sb.AppendLine("    {");
        sb.AppendLine(
            "        global::PicoMediator.MediatorAutoSubscriptionRegistry.Register("
        );
        sb.AppendLine(
            $"            \"{EscapeStringLiteral(configuratorId)}\", static container => ConfigureGeneratedHandlers(container));"
        );
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine(
            "    internal static void ConfigureGeneratedHandlers(global::PicoDI.Abs.ISvcContainer container)"
        );
        sb.AppendLine("    {");
        foreach (var s in subscribers)
        {
            sb.AppendLine("        container.Register(global::PicoDI.Abs.SvcDescriptor.Create(");
            sb.AppendLine(
                $"            typeof(global::PicoActor.Abs.IDomainEventSubscriber<{s.EventTypeFqn}>),"
            );
            sb.AppendLine($"            {EmitFactory(s)},");
            sb.AppendLine("            global::PicoDI.Abs.SvcLifetime.Transient));");
            sb.AppendLine();
        }
        foreach (var eventType in distinctEventTypes)
        {
            var bridgeName = "PicoActorEnvelopeBridge_" + SanitizeIdentifier(eventType);
            sb.AppendLine("        container.Register(global::PicoDI.Abs.SvcDescriptor.Create(");
            sb.AppendLine(
                "            typeof(global::PicoMediator.Abs.ISubscriber<global::PicoActor.Abs.DomainEventEnvelope>),"
            );
            sb.AppendLine($"            static scope => new {bridgeName}(scope),");
            sb.AppendLine("            global::PicoDI.Abs.SvcLifetime.Transient));");
            sb.AppendLine();
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        context.AddSource(
            $"PicoActorSubscriberRegistrations.{safeAssemblyName}.g.cs",
            sb.ToString()
        );
    }

    private static string EmitFactory(SubscriberInfo s)
    {
        if (s.ConstructorParameterTypes.IsEmpty)
            return $"static _ => new {s.ImplementationType}()";

        var args = string.Join(
            ", ",
            s.ConstructorParameterTypes.Select(p => $"({p})scope.GetService(typeof({p}))")
        );
        return $"static scope => new {s.ImplementationType}({args})";
    }

    private static string SanitizeIdentifier(string value) =>
        new(
            value
                .Select(c => c == '.' ? '_' : c)
                .Where(static c => char.IsLetterOrDigit(c) || c == '_')
                .ToArray()
        );

    private static string EscapeStringLiteral(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
